### ISSUE TITLE
Can I use Page Object helpers without SpecFlow?

### ISSUE THREAD

**Issue by alexeykuptsov** [quantori/Behavioral.Automation#49]
As it is said in the presentation video, SpecFlow is not supported in Rider. So can Rider users use this library to implement their page classes?

**Comment by SergeyRuzin** [comment]
Hello, sorry for late response. There has been a new plugin recently released for Rider which added Specflow support. You can find it using the link below 
https://plugins.jetbrains.com/plugin/15957-specflow-for-rider

**Comment by alexeykuptsov** [comment]
I mean, can I use your Page Object implementation in projects where BDD is used?

**Comment by Brrovko** [comment]
Yes, you can. See the Demo project. Behavioral.Automation.DemoScenarios contains BDD cases and has reference to Behavioral.Automation.DemoBindings where you can describe elements using IWebElementWrapper in a PageObject manner.
